name: Admin - Bump Minor Version
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    container: 'docker.io/kungfutrader/kungfu-builder-centos:v1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version
        uses: kungfu-trader/action-bump-version@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}