name: Release - New Version

on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*
      - release/v*/v*

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version
        id: bump-version
        uses: kungfu-trader/action-bump-version@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: "prebuild"

      - name: Docker meta
        id: docker-meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kungfutrader/kungfu-builder-centos
          tag-sha: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Show tags
        run: |
          echo show tags
          echo bump-version: [${{ steps.bump-version.outputs.tags }}]
          echo docker-meta: [${{ steps.docker-meta.outputs.tags }}]
          echo labels: [${{ steps.docker-meta.outputs.labels }}]
          echo done

      - name: Build and Push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: latest, ${{ steps.bump-version.outputs.tags }}, ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}

      - name: Push New Version To GitHub
        if: ${{ github.event.pull_request.merged }}
        uses: kungfu-trader/action-bump-version@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: "postbuild"
