name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  try:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  # try:
  #   uses: kungfu-trader/workflows/.github/workflows/.release-verify.yml@v1
  #   with:
  #     check-format: false
  #     prebuild: false
  
  verify:
    needs: try
    runs-on: ubuntu-20.04
    steps:
      - name: report
        run: echo verified
